Iter13
northmule/shorturl pull request #13
Opened 2024-08-05 17:43 UTC by northmule

2024-08-15 03:53 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Ты реализовал доработки сервиса в соответствии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Тебе удалось сохранить структуру приложения несмотря на то, что добавился новый функционал. 👍
3. Ты реализовал тесты новых сценариев и дополнил существующие. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Стоит добавить тесты новой ручки в хендлере.
2. Я бы не рекомендовал обращаться к стораджу через поле сервиса. Обращения к сервису должны происходить через его контракт (методы). Если нужен функционал стораджа непосредственно в хендлере, но не нужны все его методы, я бы рекомендовал определить интерфейс Finder. Тогда ты можешь передать сторадж в хендлер и работать с ним напрямую. Альтернативный вариант — обернуть вызов стораджа в вызов сервиса.

2024-08-15 03:53 UTC, vokinneberg commented on cmd/shortener/main.go
> +			logger.LogSugar.Errorf("Failed to open file %s: error: %s", cfg.FileStoragePath, err)
Блок с иницализацией стораджа уже как мне кажется достиг таких размеров, когда можно было бы его вынести в отдельный метод или пометить комментарием с коротким описанием того, что происодит.

2024-08-15 03:53 UTC, vokinneberg commented on cmd/shortener/main.go
> +	fmt.Println("Running server on - ", cfg.ServerURL)
У тебя же есть логгер, почему бы его здесь не использовать?

2024-08-15 03:53 UTC, vokinneberg commented on config/config.go
> +func NewConfig() (*Config, error) {
👍 Действительно, нет ни какой необходимости возвращать инрефейс.

2024-08-15 03:53 UTC, vokinneberg commented on config/config_test.go
> +			NewConfig()
Стоит добавить обработку и проверку ошибки?

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/ping_handler_test.go
> +func TestPingHandler_CheckStorageConnect(t *testing.T) {
 👍 понравилось, как ты организовал тесты.

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/ping_handler_test.go
> +			name:     "MemoryStorage",
Судя по всему имелся ввиду File?
```suggestion
			name:     " FileStorage",
```

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/ping_handler_test.go
> +type MockPostgresStorageOk struct {
Советую попробовать использовать [gomock](https://github.com/golang/mock) с кодогенерацией.

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/redirect_handler.go
> +	service *url.ShortURLService
А почему ты решил отказаться от использования интерфейса здесь?

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/routes.go
> +func AppRoutes(shortURLService *url.ShortURLService) chi.Router {
А почему ты решил отказаться от использования интерфейса здесь?

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +		modelURL, err := s.service.Storage.FindByURL(string(bodyValue))
Могу предположить, что ты заменил использование интерфейса на использование конкретного типа для того чтобы иметь возможность обращаться к  полю сервиса. Я бы не рекомендовал так делать. Обращения к сервису должны происходить через его контракт (методы). Если нужен функционал стораджа непосредственно в хендлере, но не нужны все его методы я бы рекомендовал определить интерфейс Finder:  
```go
type Finder inderface {
    FindByURL(url string) string
}
```
Тогда ты можешь передать сторадж в хендлер и работать с ним напрямую. Альтернативный вариант обернуть вызов стораджа в вызов сервиса.

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	var shortURL string
Стоит блок с переменными перенести до вызова `DecodeURL(...)`, а ошибку проверять сразу после вызова так как в противном случае теряется контекст.

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	var shortURL string
```suggestion
	var ( 
	        responseJSON JSONResponse
	        headerStatus int
	        shortURL string
	        isURLExists bool
	    )
```

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	isURLExists := false
```suggestion
```

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	}
Два похожих блока в обоих хендлерах. Можем вынести в отдельный метод?

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/services/url/shorturl.go
> +	if err != nil {
Я так полагаю, если у нас в БД стоит констрейнт на уникальность, то в случае не уникального  URL зайфейлится весь батч? Думаю стоит здесь обрабатывать это кейс так же?

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/services/url/shorturl_test.go
> +			name:    "#1_много_url",
Думаю в случае одного теста можно использовать просто сабтест `t.Run(...)`.  Но в этом случае я думаю можно реализовать больше сценариев. Например у тебя есть `wantErr`, но она не используется.

2024-08-15 03:53 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	responseItems := make([]BatchResponse, 0)
Мы же знаем длину массива, следовательно можем сразу указать capacity.
```suggestion
	responseItems := make([]BatchResponse, 0, len(responseItems))
```

2024-08-15 18:03 UTC, northmule commented on internal/app/handlers/ping_handler_test.go
> +type MockPostgresStorageOk struct {
Отличное предложение. Здесь пробовал этот способ, но в storag-ах попробовал и gomock

2024-08-15 18:06 UTC, northmule commented on internal/app/handlers/redirect_handler.go
> +	service *url.ShortURLService
Изначально я предпологал что через интерфейс я объеденю несколько разных реализаций, но в результает этого не потребовалось так как здесь скрывается один сервис.

2024-08-15 18:06 UTC, northmule commented on internal/app/handlers/routes.go
> +func AppRoutes(shortURLService *url.ShortURLService) chi.Router {
Написал выше, причина та же

2024-08-15 18:09 UTC, northmule commented on internal/app/handlers/shortener_handler.go
> +		modelURL, err := s.service.Storage.FindByURL(string(bodyValue))
Пожалуй да, верное предпложение

2024-08-16 16:24 UTC, northmule commented on internal/app/services/url/shorturl.go
> +	if err != nil {
В данном случае добавил в insert конструкцию ``` ON CONFLICT (url) where deleted_at IS NULL DO NOTHING ``` для игнорирования ошибки уникальности

2024-08-22 02:48 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +type Finder interface {
👍

2024-08-22 02:48 UTC, vokinneberg commented on internal/app/services/url/shorturl.go
> +	if err != nil {
М... OK, но вообще мне кажется по условию задачи мы должны таки обрабатывать конфликт. Оставлю это для обсуждения на следующий спринт.

2024-08-22 02:49 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью третьего спринта! 🙌  Отличная работа! 🚀 

2024-08-24 17:46 UTC, merged