Iter15
northmule/shorturl pull request #17
Opened 2024-08-28 06:16 UTC by northmule

2024-09-03 01:13 UTC, vokinneberg requested changes
Поздравляю с первым ревью четвёртого спринта! 🎉 В этом спринте мы коснулись, наверное, самых сложных тем — многопоточности и криптографии. Хочу сделать несколько предложений по улучшению и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален, корректен и проходит тесты! 🚀

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Стоит попробовать использовать кодогенерацию для моков. Слишком много ручной работы.
2. В воркере стоит каким-то образом добавить механизм управления жизненным циклом горутины, либо через канал, либо через контекст, так чтобы была возможность прервать работу горутины.
3. Стоит добавить тесты новых сценариев.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_auth.go
> +		if req.Method == http.MethodGet && req.URL.Path == "/api/user/urls" {
Я бы все-таки рекомендовал делать реализацию middleware максимально generic, и навешивать его только на те маршруты, для которых это нужно.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/handlers/ping_handler_test.go
> +func (m *MockPostgresStorageOk) Add(url models.URL) (int64, error) {
Может быть все-таки попробовать кодогенерацию? Слишком много ручной работы.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/workers/deleter_url.go
> +func (w *Worker) worker(jobCh <-chan job) {
Здесь стоит каким-то образом добавить механизм управления жизненным циклом горутины, либо через канал, либо через контекст, так что бы была возможность прервать работу горутины.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/handlers/user_urls_handler.go
> +	session *storage.SessionStorage
Здесь так же стоило бы использовать интерфейсы.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/storage/postgres_storage.go
> +	_, err := p.DB.ExecContext(ctx, migrations.Migrations01)
👍 за миграции! Единственное, из стоит выполнять в transaction scope.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/workers/deleter_url.go
> +		err := w.deleter.SoftDeletedShortURL(item.uuid, item.url)
Мне показалось, хоть у нас и используется буферизированный канал, удаление происходит по одному URL. Стоит подумать о том, как удалять их батчем.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/storage/file_storage.go
> +func (f *FileStorage) CreateUser(user models.User) (int64, error) {
Было бы здорово реализовать обратную совместимость для других типов хранилищ.

2024-09-03 01:13 UTC, vokinneberg commented on internal/app/storage/memory_storage.go
> +func (s *MemoryStorage) SoftDeletedShortURL(userUUID string, shortURL ...string) error {
Было бы здорово реализовать обратную совместимость для других типов хранилищ.

2024-09-04 05:09 UTC, northmule commented on internal/app/handlers/ping_handler_test.go
> +func (m *MockPostgresStorageOk) Add(url models.URL) (int64, error) {
Согласен на счёт кодогенерации, но здесь в учёбных целях попробовал вручную написать. Но, например при тесте стора уже применил кодогенерацию.

2024-09-05 05:54 UTC, northmule commented
Для моккирования методов к бд выбрал github.com/DATA-DOG/go-sqlmock. Оказалсь достаточно удобной.

2024-09-06 04:18 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением четвертого спринта! 🚀 Желаю удачи на выпускном проекте! 🍀

2024-09-06 06:11 UTC, merged