Iter18
northmule/shorturl pull request #20
Opened 2024-10-19 08:11 UTC by northmule

2024-10-24 03:16 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉 Этот спринт дает возможность немного отдохнуть от написания кода и при этом попробовать на практике интересные инструменты ⚡ Ты сделал улучшения своего приложения, и оно проходит автотесты 👍 Тем не менее, по традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты добавил миграции 👍
2. Твой код отформатирован с использованием `gofmt` и `goimport`.
3. Ты реализовал примеры и бенчмарки. 💪
4. Ты добавил контекст, для управления жизненным циклом приложения.

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово добавить автоматическое вычисление покрытия в CI pipeline при помощи github actions. Можно так же добавить badge, который будет показывать процент покрытия тестами проекта, в README файл. Как это сделать можно посмотреть вот здесь, например https://github.com/vladopajic/go-test-coverage
2. Мне кажется, что даже если это example, предполагается, что он будет реализован в виде теста, что предполагает проверки либо при помощи assert библиотеки, либо средствами языка Go. А так же использование `testing.T` для взаимодействия со средой. Предлагаю реализовать пример именно таким образом. Для примеров использования ручек API можно переиспользовать существующие тесты.
3. При запуске бенчмарков в проекте командой `go test -bench=. ./...` происходит ошибка `Recovered in f runtime error: invalid memory address or nil pointer dereference`. Мне кажется тут есть какая-то проблема. Попробуй разобраться в том, что происходит и поправить.
4. В логгере есть какой-то мисконцепт. Для меня вызов `NewLogger(...)` по семантике это метод, который создает логгер, но при этом он тут игнорируется, что вызывает дополнительные вопросы. Оказалось, что он и возвращает логгер и устанавливает глобальный логгер. Мне кажется, что это лишнее и добавляет ненужную сложность. Я бы рекомендовал использовать только один из подходов, причем в случае использования инстанса метод стоит назвать `NewLogger(...)` , а в случае глобального `InitLogger(...)`.
5. Я считаю, что descriptive naming очень важен в именовании тестов и бенчмарков, ведь все, что мы видим в выводе это название теста и цифры или статус выполнения. Имя `BenchmarkRedirectHandler` на самом деле дает нам информацию о том, какой метод тестируется, но не дает ни какой информации о том что именно проверяется. Было бы здорово добавить более информативное название.
6. Могу предположить, что этот интерфейс `IShortenerHandler` ни где в коде не используется по той причине, что `NewShortenerHandler(...)` возвращает `ShortenerHandler` в то время, как метод `ShortenerHandler(...)` ожидает ресивер типа `*ShortenerHandler`, что означает, что `ShortenerHandler` не реализует интерфейс. Проверить это можно используя небольшой трюк в Go - если добавить в файл cтроку `var _ IShortenerHandler = ShortenerHandler{}` мы видим ошибку компилятора. Всех этих проблем можно избежать, если определять интерфейс не там, где его реализует некий объект, а там, где он используется.
7. Попробуй все-же определять более мелкие интерфейсы и определять их там, где они используются. Это поможет немного изменить mindset, и освежить понимание языка.
8. Было бы интересно посмотреть бенчи для MemoryStorage.
9. Так как большая часть спринта была посвящена паттернам, было бы здорово если бы ты попробовал применить какой-нибудь из них в своем приложении.

Более детальные комментарии ты найдёшь в

2024-10-24 03:16 UTC, vokinneberg commented on cmd/client/example_test.go
> +func Example() {
Мне кажется, что даже если это example, предполагается, что он будет реализован в виде теста, что предполагает проверки либо при помощи assert библиотеки, либо средствами языка Go. А так же использование `testing.T` для взаимодействия со средой. Предлагаю реализовать пример именно таким образом.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/example_test.go
> +func ExamplePingHandler_CheckStorageConnect() {
Мне кажется, что даже если это example, предполагается, что он будет реализован в виде теста, что предполагает проверки либо при помощи assert библиотеки, либо средствами языка Go. А так же использование `testing.T` для взаимодействия со средой. Предлагаю реализовать пример именно таким образом.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/services/url/shorturl_test.go
> +func BenchmarkNewRandomString(b *testing.B) {
При запуске бенчмарков в проекте командой `go test -bench=. ./...` происходит ошибка `Recovered in f runtime error: invalid memory address or nil pointer dereference`. Мне кажется тут есть какая-то проблема. Попробуй разобраться в том, что происходит и поправить.

2024-10-24 03:16 UTC, vokinneberg commented on cmd/shortener/main.go
> +func run(ctx context.Context) error {
👍 за использование контекста, для управления жизненным циклом приложения.

2024-10-24 03:16 UTC, vokinneberg commented on cmd/shortener/main.go
> +	_, err := logger.NewLogger("info")
По-моему тут есть какой-то мисконцепт. Для меня вызов `NewLogger(...)` по семантике это метод, который создает логгер, но при этом он тут игнорируется, что вызывает дополнительные вопросы. Оказалось, что он и возвращает логгер и устанавливает глобальный логгер. Мне кажется, что это лишнее и добавляет ненужную сложность. Я бы рекомендовал использовать только один из подходов, причем в случае использования инстанса метод стоит назвать `NewLogger(...)` , а в случае глобального `InitLogger(...)`.

2024-10-24 03:16 UTC, vokinneberg commented on cmd/shortener/main.go
> +	if cfg.PprofEnabled {
👍 Добавить настройку это хорошая идея!

2024-10-24 03:16 UTC, vokinneberg commented on cmd/shortener/main.go
> +	return nil
Мне кажется тут можно упростить:
```suggestion
	if err != nil {
	        if errors.Is(err, http.ErrServerClosed) {
		        logger.LogSugar.Info("Сервер остановлен")
		        return nil
	        }
		return err
	}

```

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_auth.go
> +	storage url.IStorage
Дело вкуса, но вообще приставка `I` для интерфейса это все таки из мира Java или  С#. В Go обычно это не используется.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/logger.go
> +// NewResponseWriterWrapper конструктор логгера.
 Может быть можно объединить в одну запись?

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/ping_handler_test.go
> +	_, _ = logger.NewLogger("fatal")
То же самое, о чем я писал выше - без того чтобы заглянуть в детали реализации разобраться в том, что происходить сложно.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/redirect_handler_test.go
> +func BenchmarkRedirectHandler(b *testing.B) {
Я считаю, что descriptive naming очень важен в именовании тестов и бенчмарков, ведь все, что мы видим в выводе это название теста и цифры или статус выполнения. Имя  `BenchmarkRedirectHandler` на самом деле дает нам информацию о том, какой метод тестируется, но не дает ни какой информации о том что именно проверяется. Было бы здорово добавить более информативное название.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +type IShortenerHandler interface {
Могу предположить, что этот интерфейс ни где в коде не используется по той причине, что `NewShortenerHandler(...)` возвращает `ShortenerHandler` в то время, как метод `ShortenerHandler(...)` ожидает ресивер типа `*ShortenerHandler`, что означает, что `ShortenerHandler` не реализует интерфейс. Проверить это можно используя небольшой трюк в Go - если добавить в файл cтроку `var _ IShortenerHandler = ShortenerHandler{}` мы видим ошибку компилятора. Всех этих проблем можно избежать, если определять интерфейс не там, где его реализует некий объект, а там, где он используется.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/services/url/shorturl.go
> +type IStorage interface {
Попробуй все-же разделить этот суперинтерфейс на более мелкие интерфейсы и определить их там, где они используются.

2024-10-24 03:16 UTC, vokinneberg commented on internal/app/storage/memory_storage_test.go
> +func TestMemoryStorage_FindUserByLoginAndPasswordHash(t *testing.T) {
Было бы интересно посмотреть бенчи для MemoryStorage.

2024-10-24 19:03 UTC, northmule commented on internal/app/services/url/shorturl_test.go
> +func BenchmarkNewRandomString(b *testing.B) {
Кстати интересный момент, мы вроде запускаем бенчи, но сообщения летят из тестов. Эти сообщения являются результатом вывода в тестах:
```
defer func() {
			// вызов Next в FindByShortURL
			if r := recover(); r != nil {
				fmt.Println("Recovered in %v", r)
			}
		}()
```
Я таким образом ловил вызов Next, что бы тест не падал.
Убрал вывод в логгер

2024-10-24 19:09 UTC, northmule commented on internal/app/handlers/redirect_handler_test.go
> +func BenchmarkRedirectHandler(b *testing.B) {
Попробовал добавить описание вместо нэйминга через встроенный фунционал b. Насколько такой способ корреектен?

2024-10-25 14:53 UTC, northmule commented on internal/app/services/url/shorturl.go
> +type IStorage interface {
Какой-то он не выпиливаемый. Попробовал вариант с нарезкой на более мелкие интерфейсы, но видимо из за архитектуры приложения пока не удалось полностью убрать его, так как объединяет в себе все реализации стореджей

2024-10-30 02:04 UTC, vokinneberg commented on internal/app/services/url/shorturl_test.go
> +func BenchmarkNewRandomString(b *testing.B) {
Есть такое, можно попробовать запускать бенчи вот с таким флагом `-run=^$` для того чтобы попытаться убрать лишнюю информацию и вызовы.

2024-10-30 02:15 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью седьмого спринта! 🎉 

**Сильные стороны твоего PR:**

1. Ты добавил бедж, который показывает покрытие кода тестами 👍
2. Ты добавил бенчмарки для MemoryStorage.
3. Ты реализовал предложение по “упрощению” интерфейсов.

2024-10-30 02:15 UTC, vokinneberg commented on internal/app/handlers/redirect_handler_test.go
> +func BenchmarkRedirectHandler(b *testing.B) {
Конечно, это совершенно легитимный способ. 👍

2024-10-30 17:21 UTC, merged