Iter25
northmule/shorturl pull request #27
Opened 2024-11-26 15:10 UTC by northmule

2024-12-03 01:52 UTC, vokinneberg requested changes
Поздравляю с первым ревью десятого спринта! 🎉 Это последний спринт перед вторым выпускным проектом! 💪 Спринт получился насыщенный, и по традиции я хочу сделать несколько предложений по улучшению твоего кода. 🤓 

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. То, как у тебя реализовано создание интерфейсов в общем-то нормально, но я бы мог предложить более лаконичный вариант:
    - Я бы предложил перенести реализацию фабричного метода `getStorage(...)` в пакет storage.
    - Раз уж нам не обойтись без экспортируемого интерфейса, так как это то, что нам необходимо вернуть из `getStorage(...)` , я бы предложил определить интерфейс `Storage`, который будет определять общий интерфейс к хранилищу любого типа и содержать все его методы.
    - Далее, можно просто возвращать этот интерфейс из  `getStorage(...)` , который передвать в методы, которые принимают более специализированные интерфейсы типа `StatsFinder`.
    
    ```go
    package storage
    
    import (
    	"context"
    	"os"
    
    	"github.com/northmule/shorturl/config"
    	"github.com/northmule/shorturl/db"
    	"github.com/northmule/shorturl/internal/app/logger"
    	"github.com/northmule/shorturl/internal/app/storage/models"
    )
    
    type Storage interface {
    	// Add добавляет URL.
    	Add(url models.URL) (int64, error)
    	// CreateUser создание пользователя.
    	CreateUser(user models.User) (int64, error)
    	// LikeURLToUser связывает пользователя с ссылкой.
    	LikeURLToUser(urlID int64, userUUID string) error
    	// FindByShortURL поиск по короткой ссылке.
    	FindByShortURL(shortURL string) (*models.URL, error)
    	// FindByURL поиск по URL.
    	FindByURL(url string) (*models.URL, error)
    	// Ping проверка соединения с БД.
    	Ping() error
    	// MultiAdd вставка массива адресов.
    	MultiAdd(urls []models.URL) error
    	// FindUrlsByUserID поиск ссылок пользователя
    	FindUrlsByUserID(userUUID string) (*[]models.URL, error)
    	// SoftDeletedShortURL пометка ссылки как удалённой.
    	SoftDeletedShortURL(userUUID string, shortURL ...string) error
    	// GetCountShortURL количество коротких ссылок
    	GetCountShortURL() (int64, error)
    	// GetCountUser количество пользователей
    	GetCountUser() (int64, error)
    }
    
    func NewStorage(ctx context.Context, cfg *config.Config) (Storage, error) {
    	if cfg.DataBaseDsn != "" {
    		s, err := NewPostgresStorage(cfg.DataBaseDsn)
    		if err != nil {
    			logger.LogSugar.Errorf("Failed NewPostgresStorage dsn: %s, %s", cfg.DataBaseDsn, err)
    			return nil, err
    		}
    
    		logger.LogSugar.Info("Инициализация миграций")
    		migrations := db.NewMigrations(s.RawDB)
    		err = migrations.Up(ctx)
    		if err != nil {
    			return nil, err
    		}
    
    		return s, nil
    	}
    
    	if cfg.FileStoragePath != "" {
    		file, err := os.OpenFile(cfg.FileStoragePath, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
    		if err != nil {
    			logger.LogSugar.Errorf("Failed to open file %s: error: %s", cfg.FileStoragePath, err)
    			return nil, err
    		}
    		s := NewFileStorage(file)
    		return s, nil
    	}
    
    	s := NewMemoryStorage()
    	return s, nil
    }
    ```
    
2. В задании это прямо н указано, но я бы все-таки реализовал обработку  REST/gRPC в рамках одного сервиса.
    
    🤔 При выборе подхода стоит руководствоваться тем, как будет развернут сервис и как с ним будут взаимодействовать клиенты. Существует несколько подходов к разделению REST и gRPC трафика:
    
    **1️⃣ Принимать запросы на разные порты**
    
    Действительно, недостатка в портах нет, и прием REST и gRPC трафика на разных портах — достаточно простой и удобный подход. ✨ Это четко разделяет назначение портов, упрощает конфигурацию и не требует сложного мультиплексирования.
    
    **2️⃣ Общий порт с суффиксом в URL**
    
    Можно принимать вызовы на одном порте, добавив суффикс к URL:
    
    - gRPC: `localhost:8080/grpc`
    - REST: `localhost:8080/api`
    
    Это может быть удобно, когда нет возможности использовать разные порты. В принципе, ничего не мешает мультиплексировать трафик в рамках одного сервиса без префикса, но такой подход менее прозрачен и может вводить в заблуждение, не говоря уже о более сложной конфигурации. 💩
    
    **3️⃣ Разные сервисы**
    
    Можно запустить два разных сервиса для приема REST и gRPC трафика и настроить Reverse Proxy так, чтобы маршрутизация осуществлялась на соответствующий инстанс в зависимости от протокола. Такой подход удобен, если необходимо масштабировать REST и gRPC отдельно.
    
    **4️⃣ gRPC Gateway**
    
    Можно также использовать gRPC Gateway, который умеет генерировать Reverse Proxy, транслирующий запросы RESTful HTTP API в gRPC. В этом случае достаточно реализовать gRPC сервис и сгенерировать REST фасад, не дублируя функционал.
    
    🤓 В случае с публичным сервисом я бы предпочел вариант с префиксом, так как gRPC — это надстройка над HTTP/2, и по умолчанию трафик должен раздаваться с портов `80/443`. Но при развертывании в K8s или для внутренних сервисов это не так принципиально, и стоит придерживаться наиболее удобного для вас в данный момент способа.
    
    Не стоит возвращать клиенту такую детальную техническую информацию, как название метода, в котором произошла ошибка — это ему ничего не даст. Лучше записывать в логи технические детали, полезные для отладки (название пакета, метода, stack trace), а пользователю возвращать понятную бизнес-информацию. Она должна либо помочь исправить введённые данные, либо, в случае внутреннего сбоя, просто сообщить об ошибке в общих терминах. 
    
3. В общем получилась реализация двух отдельных сервисов и в результате получилось достаточно много дублирования кода. Попробуй все-таки реализовать оба протокола, как фасады для общих компонентов и свести дублирование к минимуму. 

Более детальные комментарии ты найдёшь в PR. 🤓

2024-12-03 01:52 UTC, vokinneberg commented on cmd/shortener/main.go
> +	storage, finderStats, err := getStorage(ctx, cfg)
Я бы предложил `statsFinder`, хотя это и не принципиально. 
```suggestion
	storage, statsFinder, err := getStorage(ctx, cfg)
```

2024-12-03 01:52 UTC, vokinneberg commented on cmd/shortener/main.go
> +func getStorage(ctx context.Context, cfg *config.Config) (appStorage.StorageQuery, handlers.FinderStats, error) {
То, как у тебя реализовано создание интерфейсов в общем-то нормально, но я бы мог предложить более лаконичный вариант:

- Я бы предложил перенести реализацию фабричного метода `getStorage(...)` в пакет storage.
- Раз уж нам не обойтись без экспортируемого интерфейса, так как это то, что нам необходимо вернуть из `getStorage(...)` , я бы предложил определить интерфейс `Storage`, который будет определять общий интерфейс к хранилищу любого типа и содержать все его методы.
- Далее, можно просто возвращать этот интерфейс из  `getStorage(...)` , который передвать в методы, которые принимают более специализированные интерфейсы типа `StatsFinder`.
    
    ```go
    package storage
    
    import (
    	"context"
    	"os"
    
    	"github.com/northmule/shorturl/config"
    	"github.com/northmule/shorturl/db"
    	"github.com/northmule/shorturl/internal/app/logger"
    	"github.com/northmule/shorturl/internal/app/storage/models"
    )
    
    type Storage interface {
    	// Add добавляет URL.
    	Add(url models.URL) (int64, error)
    	// CreateUser создание пользователя.
    	CreateUser(user models.User) (int64, error)
    	// LikeURLToUser связывает пользователя с ссылкой.
    	LikeURLToUser(urlID int64, userUUID string) error
    	// FindByShortURL поиск по короткой ссылке.
    	FindByShortURL(shortURL string) (*models.URL, error)
    	// FindByURL поиск по URL.
    	FindByURL(url string) (*models.URL, error)
    	// Ping проверка соединения с БД.
    	Ping() error
    	// MultiAdd вставка массива адресов.
    	MultiAdd(urls []models.URL) error
    	// FindUrlsByUserID поиск ссылок пользователя
    	FindUrlsByUserID(userUUID string) (*[]models.URL, error)
    	// SoftDeletedShortURL пометка ссылки как удалённой.
    	SoftDeletedShortURL(userUUID string, shortURL ...string) error
    	// GetCountShortURL количество коротких ссылок
    	GetCountShortURL() (int64, error)
    	// GetCountUser количество пользователей
    	GetCountUser() (int64, error)
    }
    
    func NewStorage(ctx context.Context, cfg *config.Config) (Storage, error) {
    	if cfg.DataBaseDsn != "" {
    		s, err := NewPostgresStorage(cfg.DataBaseDsn)
    		if err != nil {
    			logger.LogSugar.Errorf("Failed NewPostgresStorage dsn: %s, %s", cfg.DataBaseDsn, err)
    			return nil, err
    		}
    
    		logger.LogSugar.Info("Инициализация миграций")
    		migrations := db.NewMigrations(s.RawDB)
    		err = migrations.Up(ctx)
    		if err != nil {
    			return nil, err
    		}
    
    		return s, nil
    	}
    
    	if cfg.FileStoragePath != "" {
    		file, err := os.OpenFile(cfg.FileStoragePath, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
    		if err != nil {
    			logger.LogSugar.Errorf("Failed to open file %s: error: %s", cfg.FileStoragePath, err)
    			return nil, err
    		}
    		s := NewFileStorage(file)
    		return s, nil
    	}
    
    	s := NewMemoryStorage()
    	return s, nil
    }
    ```

2024-12-03 01:52 UTC, vokinneberg commented on cmd/shortener_grpc/main.go
> +func main() {
В задании это прямо н указано, но я бы все-таки реализовал обработку  REST/gRPC в рамках одного сервиса.

🤔 При выборе подхода стоит руководствоваться тем, как будет развернут сервис и как с ним будут взаимодействовать клиенты. Существует несколько подходов к разделению REST и gRPC траффика:

**1️⃣ Принимать запросы на разные порты**

Действительно, недостатка в портах нет, и прием REST и gRPC траффика на разных портах — достаточно простой и удобный подход. ✨ Это четко разделяет назначение портов, упрощает конфигурацию и не требует сложного мультиплексирования.

**2️⃣ Общий порт с суффиксом в URL**

Можно принимать вызовы на одном порте, добавив суффикс к URL:

- gRPC: `localhost:8080/grpc`
- REST: `localhost:8080/api`

Это может быть удобно, когда нет возможности использовать разные порты. В принципе, ничего не мешает мультиплексировать трафик в рамках одного сервиса без префикса, но такой подход менее прозрачен и может вводить в заблуждение, не говоря уже о более сложной конфигурации. 💩

**3️⃣ Разные сервисы**

Можно запустить два разных сервиса для приема REST и gRPC траффика и настроить Reverse Proxy так, чтобы маршрутизация осуществлялась на соответствующий инстанс в зависимости от протокола. Такой подход удобен, если необходимо масштабировать REST и gRPC отдельно.

**4️⃣ gRPC Gateway**

Можно также использовать gRPC Gateway, который умеет генерировать Reverse Proxy, транслирующий запросы RESTful HTTP API в gRPC. В этом случае достаточно реализовать gRPC сервис и сгенерировать REST фасад, не дублируя функционал.

🤓 В случае с публичным сервисом я бы предпочел вариант с префиксом, так как gRPC — это надстройка над HTTP/2, и по умолчанию трафик должен раздаваться с портов `80/443`. Но при развертывании в K8s или для внутренних сервисов это не так принципиально, и стоит придерживаться наиболее удобного для вас в данный момент способа.

2024-12-03 01:52 UTC, vokinneberg commented on cmd/shortener_grpc/main.go
> +func getStorage(ctx context.Context, cfg *config.Config) (appStorage.StorageQuery, handlers.FinderStats, error) {
Здесь перенос `getStorage` в общий пакет так же поможет уменьшить дублирование.

2024-12-03 01:52 UTC, vokinneberg commented on cmd/shortener_grpc/main.go
> +func printLabel() {
Так же было бы здорово убрать в какой-то расшаренный хелпер, хотя в случае с одним сервисом этого не понадобится.

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_trusted_subnet.go
> +			logger.LogSugar.Infof("доверенная сеть не заданна, доступ ограничен")
Мне кажется, такая реализация противоречит требованиям - _При пустом значении переменной `trusted_subnet` метрики должны обрабатываться сервером без дополнительных ограничений._

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_trusted_subnet.go
> +			logger.LogSugar.Infof("не передан IP адрес, доступ ограничен")
Я бы рекомендовал такие сообщения писать на уровне `Warn` - все-таки это не совсем штатная ситуация.

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_trusted_subnet_test.go
> +	assert.Equal(t, http.StatusForbidden, res.Code)
Было бы здорово добавлять к ассертам информативное сообщение.

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/routes.go
> +	statsURI   = "/api/internal/stats"
В случае с маршрутами не уверен, что выносить их в константы хорошая идея, так как они все-же один раз используются и если использовать из явно это мне кажется более наглядным.

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/stats_handler.go
> +		http.Error(res, "error GetCountUser()", http.StatusInternalServerError)
Не стоит возвращать клиенту такую детальную техническую информацию, как название метода, в котором произошла ошибка — это ему ничего не даст. Лучше записывать в логи технические детали, полезные для отладки (название пакета, метода, stack trace), а пользователю возвращать понятную бизнес-информацию. Она должна либо помочь исправить введённые данные, либо, в случае внутреннего сбоя, просто сообщить об ошибке в общих терминах.

2024-12-03 01:52 UTC, vokinneberg commented on internal/app/handlers/stats_handler_test.go
> +	stor := storage.NewMemoryStorage()
```suggestion
	store := storage.NewMemoryStorage()
```

2024-12-03 01:52 UTC, vokinneberg commented on internal/grpc/handlers/interceptors/auth.go
> +		logger.LogSugar.Infof("Куки не переданы, создаю нового пользователя с uuid %s", userUUID)
Почему то текст на кириллице? Я бы рекомендовал все же унифицировать сообщения и использовать либо кириллицу, либо латиницу.

2024-12-03 01:52 UTC, vokinneberg commented on internal/grpc/handlers/interceptors/auth.go
> +func NewCheckAuth(userCreator middlewarehandler.UserCreator, session storage.SessionAdapter) *CheckAuth {
 Можно ли как-то выделить этот код в общий пакет и использовать его для middleware и для interceptors?

2024-12-03 01:52 UTC, vokinneberg commented on internal/grpc/handlers/interceptors/check_trusted_subnet.go
> +func (c *CheckTrustedSubnet) GrantAccess(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
Можно ли как-то выделить этот код в общий пакет и использовать его для middleware и для interceptors?

2024-12-04 18:18 UTC, northmule commented on cmd/shortener_grpc/main.go
> +func main() {
Попробовал реализовать через gateway (отдельно в shortener_gw что бы не сломать текущую реализацию). Работает оно так что http запросы теперь обрабатываются хэндлерами написанными для grpc и запросы grpc так же обрабатываются этими хэндлерами.
Тогда как реализовать обратную ситуацию (если это возможно), что бы в обработке участвовали ранее написанный хэндлеры для http и эти же хэндлеры обрабатывали и http и grpc запросы ?

2024-12-04 18:18 UTC, northmule commented on cmd/shortener_grpc/main.go
> +func printLabel() {
Пока оставил, так как реализовал в разных main

2024-12-04 18:21 UTC, northmule commented on internal/app/handlers/middlewarehandler/check_trusted_subnet.go
> +			logger.LogSugar.Infof("доверенная сеть не заданна, доступ ограничен")
Здесь не соглашусь всё же, так как в ТЗ такая информация: (Сервис сокращения URL)
_При пустом значении переменной trusted_subnet доступ к эндпоинту должен быть запрещён для любого входящего запроса._

2024-12-11 03:12 UTC, vokinneberg commented on cmd/shortener_grpc/main.go
> +func main() {
Похоже, что обратное при помощи https://github.com/grpc-ecosystem/grpc-gateway не получится сделать, так как эта реализация основана на `proto` файлах, а это предполагает, что gRPC API уже описано. Интересно было бы запустить автотесты для гейтвея.

2024-12-11 03:13 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/check_trusted_subnet.go
> +			logger.LogSugar.Infof("доверенная сеть не заданна, доступ ограничен")
Все правильно, я перепутал с сервисом метрик, там как раз обратное требование 😊

2024-12-11 03:17 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением 10-го спринта! 🎉 Твой уровень владения средствами языка и принятия осознанных решений здорово вырос. Так держать 🙌

2024-12-11 05:32 UTC, merged