Iter9
northmule/shorturl pull request #9
Opened 2024-07-17 18:55 UTC by northmule

Iter9

2024-07-24 00:31 UTC, vokinneberg requested changes
Поздравляю с первым ревью второго спринта! 🤗  В этом спринте мы охватили большой и важный материал, а наше приложение усложнилось. 💪 Ты справился с реализацией и реализовал все в соотвествии с постановкой задачи. Отличная работа! 🚀 Тем не менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓 Так же предлагаю запланировать встречу 1 на 1, где мы могли бы обсудить review 🤝

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты реализовал тесты новых сценариев и дополнил существущие. 👍
3. Ты добавил более информативные сообщения в своих тестах 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Мне показалось, что после добавления filestorage структура сервиса стала довольно сложной. Я бы предложил использовать filestorage вместо storage, так как они друг друга дублируют. Был бы рад обсудить, как это можно сделать.
2. Заметил, что ты упустил пару сценариев, которые можно было бы добавить.
3. Реализация compress middleware достаточно сложная тема и у тебя получилось отлично. 👍 Я бы все же предложил попробовать упростить логику самого хендлера.

2024-07-24 00:31 UTC, vokinneberg commented on config/config.go
>  		_ = fmt.Errorf("parse error os.Args: %s", err)
Не совсем понимаю для чего нужна эта строчка? Ты добавляешь к ошибке контекст и далее ее игнорируешь. Я бы рекомендовал вывести информационное сообщение при помощи логирования о том, что произошло.

2024-07-24 00:31 UTC, vokinneberg commented on config/config.go
> +	flagFileStoragePath := configFlag.String("f", "/tmp/short-url-db.json", "the path to the file for storing links")
Возможно стоит вынести значение по-умолчанию в константы, как и другие значения?

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main.go
> +func restoreStorageData(file string, storage *appStorage.Storage) {
Почему бы не реализовать эту функцию внутри `storage` и не вызывать ее в момент создания  `NewStorage()`? Если хочется иметь возможность управлять тем будет ли восстановлен стейт или нет можно передавать флаг в этот метод `NewStorage(restore bool)`.

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main.go
> +	if file == "" {
Если имя файла не передали, будем дальше использовать in memory сторадж? Возможно стоит возвращать в этом случае ошибку?

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main.go
> +		log.Fatal(err)
Не стоит в этом месте приложения вызывать `log.Fatal(...)`. Вообще я бы рекомендовал вызывать эту функцию там, где мы явно намерены завершит приложение, например в entry point приложения, тем более, что в твоем приложении это уже реализовано. Я бы рекомендовал так же обработать ошибку и вернуть ее в вызывающий код. Это касается и дальнейшей обработки ошибок.

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main.go
> +		logger.Log.Sugar().Info(err)
У нас произошла ошибка? Не правильнее ли ее будет залогировать на уровне `Error` или хотя бы `Warning`. Если уровень логирования для приложения будет понижен до Error или Warning пользователь эти ошибки не увидит.

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +	t.Run("првоерка_восстановления_значений_из_файла", func(t *testing.T) {
Я так понимаю, что тут тестируется только позитивный кейс. Было бы здорово добавить негативные кейсы в том числе.

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +				t.Error("Значений не найдено")
Было бы здорово добавить более информативные сообщение о том, что пошло не так.
```suggestion
				t.Errorf("FindByURL(%s) = %s, значений не найдено", url.URL, modelURL)
```

2024-07-24 00:31 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +			}
Так же было бы здорово добавить проверку того, что в хранилище загрузились именно те данные, которые были в файле.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/gzipcompressor.go
> +		expectedContentTypes := map[string]bool{
Можно вынести за пределы функции `MiddlewareGzipCompressor`. Таким образом мапа будет инициализирвоаться только один раз и переиспользоваться разными запросами.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/gzipcompressor.go
> +		}
Я бы советовал тут, как и далее, использовать метод `Get()` для получения значения хедера. Так можно достаточно сильно упростить и сократить код.

```suggestion
		requestContentType := request.Header.Get("Content-Type")
		if _, ok := expectedContentTypes[requestContentType]; !ok {
			logger.Log.Sugar().Infof("Ответ сервера не сжимается, для Content-type не поддерживается сжатие")
			next.ServeHTTP(response, request)
			return
		}
```

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/gzipcompressor.go
> +			defer gzipWriter.Close()
Было бы здорово, если мы сжимаем контент устанавливать хедер `Content-Length` для ответа.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/middlewarehandler/logger.go
> +		sugarLogger := logger.Log.Sugar()
Если у нас везде используется `logger.Log.Sugar()` возможно стоит сразу установить глобальный логер, как  `logger.Log.Sugar()`?

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +var regexMustCompileURL = regexp.MustCompile(`(http|https)://\S+`)
👍 за вынос компиляции регэксп выражения на уровень пакета! Единственное мне кажется нет особой ценности в именовании переменной `regexMustCompileURL`, я бы предложил упростить: 
 
```suggestion
var regexURL = regexp.MustCompile(`(http|https)://\S+`)
```

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	defer req.Body.Close()
В своих review я просил закрывать http request body
```go
     defer r.Body.Close()
```
На самом деле это делать не обязательно (хотя и не запрещается), так как согласно документации The Server will close the request body. The ServeHTTP. Handler does not need to.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +type JSONRequest struct {
Я бы предложил более информативное имя ведь типов запросов может быть много:
```suggestion
type ShortenerRequest struct {
```

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/shortener_handler.go
> +	Result string `json:"result,omitempty"`
`omitempty` означает, что в случае пустой строки это поле вообще будет отсутствовать в JSON. Мы точно этого хотим?

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/handlers/shortener_handler_test.go
> +			return
Не обязательно в тесте после  `t.Error()` возвращать управление `return`. Если дальнейшее выполнения теста не имеет смысла, можно использовать  `t.Fatalf()`.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/services/compressor/compressor.go
> +	Gz       *gzip.Writer
Я бы рекомендовал назвать поля в GzipWriter и GzipReader по разному - очень легко из перепутать, учитывая, что они в одном файле.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/storage/models/url.go
> +	ID       uint   `json:"id,omitempty"`
Есть ли причина почему мы хотим исключать только пустой `ID`?

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/services/filestorage/filestorage.go
> +	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0666)
Я не рекомендую сохранять хендлер открытого файла на уровне структуры, что будет если файл закроется? Предлагаю открывать и закрывать файл при каждой операции записи/чтения.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/services/filestorage/filestorage.go
> +package filestorage
Не совсем понимаю в чем преимущество разделения на `Setter` и `Getter`, а так же мне кажется, что в приложении получилось слишком много слоев и его стало достаточно сложно ментально воспринимать. Я бы рекомендовал реализовать filestorage так же, как реализован storage причем так чтобы они реализовывали один и тот же интерйфейс, а shortURLService работал бы с той или иной реализацией в зависимости от того, какой инстанс был передан в момент создания приложения.

2024-07-24 00:31 UTC, vokinneberg commented on internal/app/services/filestorage/filestorage.go
> +	idNum := 1
А как будет инициализирвоаться счетчик ID между вызовами `ReadURLAll()`? ID каждый раз будет разный?

2024-07-25 10:21 UTC, northmule commented on cmd/shortener/main_test.go
> +			}
В данном случе идёт перебор мапы, которая предварительно сохраняется в файл и далее поиск по стору, т.е проверка происходит.

2024-07-25 11:27 UTC, northmule commented on internal/app/storage/models/url.go
> +	ID       uint   `json:"id,omitempty"`
Пока это модель используется в том числе для хранения в памяти, то наверное логично что ID можно и исключить

2024-07-25 11:28 UTC, northmule commented on internal/app/handlers/middlewarehandler/gzipcompressor.go
> +			defer gzipWriter.Close()
добавил в метод Write для этого типа

2024-08-03 02:11 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью второго спринта! 🙌 Ты реализовал мои предложения, и мне кажется, твой код стал более консистентным и лаконичным. Отличная работа! 🚀 

2024-08-03 02:11 UTC, vokinneberg commented on cmd/shortener/main.go
> +	_, err = config.Init()
А почему мы не используем этот кофиг, который тут возвращается?

2024-08-03 02:11 UTC, vokinneberg commented on internal/app/services/url/shorturl.go
> +type StorageInterface interface {
В Go существует нотация в соотвествии с которой интерфейс именуется по тому, что он делает + приставка er. В данном случае напрашивается название `SaverFinder`, а суффикс Interface мне кажется можно опустить.

2024-08-03 02:11 UTC, vokinneberg commented on internal/app/storage/file_storage.go
> +type FileStorage struct {
👍 за реализацию!

2024-08-03 02:11 UTC, vokinneberg commented on internal/app/storage/file_storage.go
> +func (f *FileStorage) restoreStorage() {
👍 мне кажется, так намного лучше!

2024-08-03 02:11 UTC, vokinneberg commented on internal/app/storage/file_storage_test.go
> +func TestFileStorage_restoreStorageData(t *testing.T) {
👍 за тесты Storage.

2024-08-04 16:59 UTC, merged